fix: add checks for peripheral.mtu
abandonware/noble pull request #165
Opened 2021-01-24 22:46 UTC by fisherwise

checks if it's valid when setting it.
Should fix the TypeError of it

2021-02-14 16:10 UTC, rzr commented
please rebase

2021-02-14 16:10 UTC, rzr commented on lib/noble.js
> +  if (peripheral && peripheral.mtu && mtu) peripheral.mtu = mtu;
or maybe :    var peripheral = this._peripherals[peripheralUuid] || {} ?

2021-03-12 19:49 UTC, rzr commented
can you please try to update your branch ?

2021-03-17 01:40 UTC, fisherwise commented on lib/noble.js
> +  if (peripheral && peripheral.mtu && mtu) peripheral.mtu = mtu;
> or maybe : var peripheral = this._peripherals[peripheralUuid] || {} ?

if ```peripheral = {}``` then ```peripheral.mtu``` will get TypeError i guess? same for ```if (peripheral)``` when accessing ```.mtu```

2021-03-17 02:00 UTC, fisherwise commented
@rzr sry for the late reply just rebased it

2021-03-17 08:58 UTC, rzr commented on lib/noble.js
> +  if (peripheral && peripheral.mtu && mtu) peripheral.mtu = mtu;
if peripheral = {} then peripheral.mtu is undefined but you can do affectation:

``
node
Welcome to Node.js v14.15.0.
Type ".help" for more information.
> var p = {};
undefined
> p.foo = true;
true
> console.log( p.as)
undefined


```

2021-03-17 08:58 UTC, rzr requested changes
could be simplified

2021-03-27 02:34 UTC, fisherwise reviewed
But this is to fix TypeError. Checked with typescript and yields error

2021-03-30 14:13 UTC, merged