Improve eslint
abandonware/noble pull request #171
Opened 2021-02-06 08:35 UTC by atrovato

Based on #155 comment: split PR eslint first :)

2021-02-06 08:37 UTC, atrovato commented on .eslintrc.js
> +    semi: "error"
@rzr you commented:
> please explain why this was changed ?

As file content is json, quotes are not required here.

2021-02-06 09:34 UTC, atrovato commented on package.json
> +    "lint-fix": "eslint \"**/*.js\" --fix",
I use `\"` to be able to run on windows env.

2021-02-09 23:04 UTC, rzr commented
Please add a change to ignore modules too ie :

https://github.com/abandonware/noble/pull/171/checks?check_run_id=1844386700# 

```
s/home/runner/work/noble/noble/node_modules/mocha/lib/mocha.js:1215for await (const fixtureFn of fixtureFns) {^^^^^
```

2021-02-11 20:23 UTC, atrovato commented
This error is not linked to eslint but to node 8 build. Should I do in this PR or in a separate one?

2021-02-13 14:37 UTC, atrovato commented
With eslint 7, node 8 is no longer supported

https://eslint.org/docs/user-guide/migrating-to-7.0.0#nodejs-8-is-no-longer-supported

2021-02-13 14:49 UTC, atrovato commented
And `As of v8.0.0, Mocha requires Node.js v10.12.0 or newer.`

https://mochajs.org/#installation

2021-02-13 15:04 UTC, atrovato commented
Ok I changed `nodepackage.yml` to ignore lin on node 8, and to use mocha 7.2.0 on node 8.

2021-02-13 15:32 UTC, rzr commented
sounds good to me

2021-02-13 15:34 UTC, rzr requested changes
please open new pr with this change : https://github.com/abandonware/noble/pull/171/commits/b76fa34ab1b8e27299b49eb29ae2741da01cc5d5#diff-b29da93bc686f97c01ba07c233850a8c2a21d53cbe9bfc153f905640106da66b and then your eslint fixes then you can rebase everything to make sure nothing break

2021-02-14 15:33 UTC, rzr requested changes
please rebase with only eslint changes

2021-02-14 15:55 UTC, atrovato commented
Done :)

2021-02-14 16:09 UTC, rzr approved these changes

2021-02-14 16:09 UTC, merged